#!/usr/bin/env bash
set -e
export DISPLAY=:99
Xvfb :99 -screen 0 1920x1080x24 & sleep 1
fluxbox &
x11vnc -display :99 -nopw -forever -shared -rfbport 5900 &
websockify --web=/usr/share/novnc/ 6080 localhost:5900