global:
  checkNewVersion: true
  sendAnonymousUsage: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: ":443"
    http:
      tls:
        certResolver: myresolver
        domains:
          - main: ${N8N_HOST}

certificatesResolvers:
  myresolver:
    acme:
      email: ${TRAEFIK_ACME_EMAIL}
      storage: /acme/acme.json
      httpChallenge:
        entryPoint: web

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

accessLog:
  filePath: /var/log/traefik/access.log
  bufferingSize: 100
  filters:
    statusCodes:
      - "400-499"
      - "500-599"

log:
  level: INFO
  filePath: /var/log/traefik/traefik.log

api:
  dashboard: true
  insecure: false

serversTransport:
  maxIdleConnsPerHost: 100
  forwardingTimeouts:
    dialTimeout: 10s
    responseHeaderTimeout: 10s
  insecureSkipVerify: false
