version: '3.8'
services:
  cassandra_master:
    image: cassandra:latest
    container_name: cassandra_master
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCassandraCluster
      - CASSANDRA_LISTENER_RPC_ADDRESS=0.0.0.0
      - CASSANDRA_LISTENER_ADDRESS=0.0.0.0
      - CASSANDRA_BROADCAST_ADDRESS=cassandra_master
      - CASSANDRA_SEEDS=cassandra_master
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_NUM_TOKENS=256
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data_master:/var/lib/cassandra
    networks:
      - cassandra_network
    depends_on:
      - cassandra_slave1
      - cassandra_slave2

  cassandra_slave1:
    image: cassandra:latest
    container_name: cassandra_slave1
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCassandraCluster
      - CASSANDRA_LISTENER_RPC_ADDRESS=0.0.0.0
      - CASSANDRA_LISTENER_ADDRESS=0.0.0.0
      - CASSANDRA_BROADCAST_ADDRESS=cassandra_slave1
      - CASSANDRA_SEEDS=cassandra_master
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
    ports:
      - "9043:9042"
    volumes:
      - cassandra_data_slave1:/var/lib/cassandra
    networks:
      - cassandra_network

  cassandra_slave2:
    image: cassandra:latest
    container_name: cassandra_slave2
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCassandraCluster
      - CASSANDRA_LISTENER_RPC_ADDRESS=0.0.0.0
      - CASSANDRA_LISTENER_ADDRESS=0.0.0.0
      - CASSANDRA_BROADCAST_ADDRESS=cassandra_slave2
      - CASSANDRA_SEEDS=cassandra_master
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
    ports:
      - "9044:9042"
    volumes:
      - cassandra_data_slave2:/var/lib/cassandra
    networks:
      - cassandra_network

volumes:
  cassandra_data_master:
  cassandra_data_slave1:
  cassandra_data_slave2:

networks:
  cassandra_network:
    driver: bridge
